import React from 'react';
import BibleVerse from '../utils/BibleVerse'

const WhatWeBelieveSection = (props) => {
  return (
    <div>
      <h2>Our Beliefs</h2>
      <h4>The Scriptures</h4>
      <p>We believe in the verbal inspiration, total inerrancy and infallibility of the Holy Scriptures in their entirety. These being God breathed, we believe the bible to be solely-sufficient and the final authority in all matters of faith, doctrine and practice. 
        (<BibleVerse reference="1TH.2.13" text="1 Thessalonians 2:13"/>,
        <BibleVerse reference="2TI.3.16" text="2 Timothy 3:16"/>)</p>

      <div id="contentRight">
        <h4>The Bible</h4>
        <p>1. Both the Old and New Testament Scriptures are verbally inspired by God, inerrant in the original manuscripts, and are the ultimate authorities in all areas of faith and practice and,</p>
        <p>2. The Scriptures should be interpreted literally whenever possible, consistently, contextually, grammatically, culturally and historically.</p>
        <p><em><a href="http://biblia.com/bible/esv/Psalm%2019.7-11" class="lbsBibleRef" data-reference="Psalm 19.7-11" data-version="esv" target="_blank">Psalm 19:7-11</a>; <a href="http://biblia.com/bible/esv/Psalm%20119.160" class="lbsBibleRef" data-reference="Psalm 119.160" data-version="esv" target="_blank">Psalm 119:160</a>; <a href="http://biblia.com/bible/esv/Romans%207.5" class="lbsBibleRef" data-reference="Romans 7.5" data-version="esv" target="_blank">Romans 7:5</a>; <a href="http://biblia.com/bible/esv/2%20Timothy%203.16-17" class="lbsBibleRef" data-reference="2 Timothy 3.16-17" data-version="esv" target="_blank">2 Timothy 3:16-17</a>; <a href="http://biblia.com/bible/esv/Revelation%2022.18-19" class="lbsBibleRef" data-reference="Revelation 22.18-19" data-version="esv" target="_blank">Revelation 22:18-19</a>. </em></p>
        <h2>God</h2>
        <p>1. We believe that the Godhead, also known as "The Trinity," eternally exists in three persons: GOD THE FATHER, GOD THE SON, GOD THE HOLY SPIRIT. They are one God, having the same nature, attributes and perfection.</p>
        <p><em><a href="http://biblia.com/bible/esv/Isaiah%2048.16" class="lbsBibleRef" data-reference="Isaiah 48.16" data-version="esv" target="_blank">Isaiah 48:16</a>; <a href="http://biblia.com/bible/esv/Matthew%2028.19" class="lbsBibleRef" data-reference="Matthew 28.19" data-version="esv" target="_blank">Matthew 28:19</a>; <a href="http://biblia.com/bible/esv/John%2017.5" class="lbsBibleRef" data-reference="John 17.5" data-version="esv" target="_blank">John 17.5</a>; <a href="http://biblia.com/bible/esv/Romans%201.20" class="lbsBibleRef" data-reference="Romans 1.20" data-version="esv" target="_blank">Romans 1:20</a>; <a href="http://biblia.com/bible/esv/2%20Corinthians%2013.14" class="lbsBibleRef" data-reference="2 Corinthians 13.14" data-version="esv" target="_blank">2 Corinthians 13:14</a>.</em></p>
        <p>2. We believe that the Father is perfect in holiness, almighty in power, and infinite in wisdom. As the Creator of all, He is the Father to all men, but, He is a spiritual Father only to those who believe in the Lord Jesus Christ.</p>
        <p><em><a href="http://biblia.com/bible/esv/Psalm%20145.8-9" class="lbsBibleRef" data-reference="Psalm 145.8-9" data-version="esv" target="_blank">Psalm 145:8-9</a>; <a href="http://biblia.com/bible/esv/Matthew%205.45" class="lbsBibleRef" data-reference="Matthew 5.45" data-version="esv" target="_blank">Matthew 5:45</a>; <a href="http://biblia.com/bible/esv/Matthew%206.24-34" class="lbsBibleRef" data-reference="Matthew 6.24-34" data-version="esv" target="_blank">6:24-34</a>; <a href="http://biblia.com/bible/esv/John%2014.6" class="lbsBibleRef" data-reference="John 14.6" data-version="esv" target="_blank">John 14:6</a>; <a href="http://biblia.com/bible/esv/1%20Timothy%202.5" class="lbsBibleRef" data-reference="1 Timothy 2.5" data-version="esv" target="_blank">1 Timothy 2:5</a>. </em></p>
        <p>3. We believe in the personality and deity of the Lord Jesus Christ, begotten of the Holy Spirit, born of the virgin Mary, truly God and truly Man. We believe in His sinless life, His vicarious atonement for the sins of mankind by the shedding of His blood on the cross and in His bodily resurrection from the tomb.</p>
        <p><em><a href="http://biblia.com/bible/esv/Matthew%201.20" class="lbsBibleRef" data-reference="Matthew 1.20" data-version="esv" target="_blank">Matthew 1:20</a>; <a href="http://biblia.com/bible/esv/Luke%201.30-37" class="lbsBibleRef" data-reference="Luke 1.30-37" data-version="esv" target="_blank">Luke 1:30-37</a>; <a href="http://biblia.com/bible/esv/John%201.1" class="lbsBibleRef" data-reference="John 1.1" data-version="esv" target="_blank">John 1:1</a>, <a href="http://biblia.com/bible/esv/John%201.14" class="lbsBibleRef" data-reference="John 1.14" data-version="esv" target="_blank">1:14</a>, <a href="http://biblia.com/bible/esv/John%2010.30" class="lbsBibleRef" data-reference="John 10.30" data-version="esv" target="_blank">10:30</a>; <a href="http://biblia.com/bible/esv/Philippians%202.5-7" class="lbsBibleRef" data-reference="Philippians 2.5-7" data-version="esv" target="_blank">Philippians 2:5-7</a>; <a href="http://biblia.com/bible/esv/Colossians%201.19" class="lbsBibleRef" data-reference="Colossians 1.19" data-version="esv" target="_blank">Colossians 1:19</a>; <a href="http://biblia.com/bible/esv/1%20Timothy%203.16" class="lbsBibleRef" data-reference="1 Timothy 3.16" data-version="esv" target="_blank">1 Timothy 3:16</a>. </em></p>
        <p>4. We believe that the Holy Spirit is the divine third person of the Godhead, and thereby co-equal with the Father and the Son. He is the infallible interpreter of the Word of God. He convicts man of sin; indwells every believer; is ever present to testify of Christ; regenerates; baptizes; seals the believer; guides; teaches; empowers the life of the believer and is vitally involved in the sanctification of the believer.</p>
        <p><em><a href="http://biblia.com/bible/esv/John%203.5" class="lbsBibleRef" data-reference="John 3.5" data-version="esv" target="_blank">John 3:5</a>, <a href="http://biblia.com/bible/esv/John%203.6" class="lbsBibleRef" data-reference="John 3.6" data-version="esv" target="_blank">6</a>,<a href="http://biblia.com/bible/esv/John%203.8" class="lbsBibleRef" data-reference="John 3.8" data-version="esv" target="_blank">8</a>; <a href="http://biblia.com/bible/esv/John%2014.16-18" class="lbsBibleRef" data-reference="John 14.16-18" data-version="esv" target="_blank">14:16-18</a>; <a href="http://biblia.com/bible/esv/John%2016.8-11" class="lbsBibleRef" data-reference="John 16.8-11" data-version="esv" target="_blank">16:8-11</a>; <a href="http://biblia.com/bible/esv/Romans%208.9" class="lbsBibleRef" data-reference="Romans 8.9" data-version="esv" target="_blank">Romans 8:9</a>; <a href="http://biblia.com/bible/esv/I%20Corinthians%2012.13" class="lbsBibleRef" data-reference="I Corinthians 12.13" data-version="esv" target="_blank">I Corinthians 12:13</a>; <a href="http://biblia.com/bible/esv/2%20Corinthians%203.18" class="lbsBibleRef" data-reference="2 Corinthians 3.18" data-version="esv" target="_blank">2 Corinthians 3:18</a>; <a href="http://biblia.com/bible/esv/Ephesians%201.13" class="lbsBibleRef" data-reference="Ephesians 1.13" data-version="esv" target="_blank">Ephesians 1:13</a>; <a href="http://biblia.com/bible/esv/Ephesians%205.18" class="lbsBibleRef" data-reference="Ephesians 5.18" data-version="esv" target="_blank">5:18</a>.</em></p>
        <h2>Creation</h2>
        <p>We believe that the account of the six day creation as given in the Book of Genesis is to be literally understood and that creation was a direct act of God. Therefore we teach that any evolutionary hypothesis is totally inconsistent with the Scriptures.</p>
        <p><em><a href="http://biblia.com/bible/esv/Genesis%201.1-2.25" class="lbsBibleRef" data-reference="Genesis 1.1-2.25" data-version="esv" target="_blank">Genesis 1:1-2:25</a>; <a href="http://biblia.com/bible/esv/John%201.3-%2010" class="lbsBibleRef" data-reference="John 1.3- 10" data-version="esv" target="_blank">John 1:3- 10</a>; <a href="http://biblia.com/bible/esv/Colossians%201.%2016" class="lbsBibleRef" data-reference="Colossians 1. 16" data-version="esv" target="_blank">Colossians 1: 16</a>.</em></p>
        <h2>Mankind&nbsp;</h2>
        <p>1. Man was directly and immediately created by God in His likeness, free of sin, with a rational nature, intelligence, volition, self-determination, and moral responsibility to God; and,</p>
        <p>2. God's intention in the creation of man was that man should glorify God, enjoy His fellowship, live his life in the will of God, and by this accomplish God's purpose for him.</p>
        <p><em><a href="http://biblia.com/bible/esv/Genesis%202.7" class="lbsBibleRef" data-reference="Genesis 2.7" data-version="esv" target="_blank">Genesis 2:7</a>, <a href="http://biblia.com/bible/esv/Genesis%202.15-25" class="lbsBibleRef" data-reference="Genesis 2.15-25" data-version="esv" target="_blank">15-25</a>; <a href="http://biblia.com/bible/esv/Isaiah%2043.7" class="lbsBibleRef" data-reference="Isaiah 43.7" data-version="esv" target="_blank">Isaiah 43:7</a>, <a href="http://biblia.com/bible/esv/Colossians%201.16" class="lbsBibleRef" data-reference="Colossians 1.16" data-version="esv" target="_blank">Colossians 1:16</a>; <a href="http://biblia.com/bible/esv/James%203.9" class="lbsBibleRef" data-reference="James 3.9" data-version="esv" target="_blank">James 3:9</a>; <a href="http://biblia.com/bible/esv/Revelation%204.11" class="lbsBibleRef" data-reference="Revelation 4.11" data-version="esv" target="_blank">Revelation 4:11</a>. </em></p>
        <h2>Sin&nbsp;</h2>
        <p>We believe that, in Adam's sin of disobedience to the revealed will and Word of God, man lost his innocence; incurred the penalty of spiritual and physical death; became subject to the wrath of God; and became inherently corrupt and apart from divine grace utterly incapable of choosing or doing that which is acceptable to God. With no recuperative powers to enable him to recover himself, man is hopelessly lost. Therefore, man's salvation is wholly dependent upon the redemptive work of our Lord Jesus Christ.</p>
        <p><em><a href="http://biblia.com/bible/esv/Genesis%202.17" class="lbsBibleRef" data-reference="Genesis 2.17" data-version="esv" target="_blank">Genesis 2:17</a>, <a href="http://biblia.com/bible/esv/Genesis%203.1-19" class="lbsBibleRef" data-reference="Genesis 3.1-19" data-version="esv" target="_blank">3:1-19</a>; <a href="http://biblia.com/bible/esv/John%203.36" class="lbsBibleRef" data-reference="John 3.36" data-version="esv" target="_blank">John 3:36</a>; <a href="http://biblia.com/bible/esv/Romans%203.23" class="lbsBibleRef" data-reference="Romans 3.23" data-version="esv" target="_blank">Romans 3:23</a>; <a href="http://biblia.com/bible/esv/Romans%206.23" class="lbsBibleRef" data-reference="Romans 6.23" data-version="esv" target="_blank">6:23</a>; <a href="http://biblia.com/bible/esv/1%20Corinthians%202.14" class="lbsBibleRef" data-reference="1 Corinthians 2.14" data-version="esv" target="_blank">1 Corinthians 2:14</a>; <a href="http://biblia.com/bible/esv/Ephesians%202.1-3" class="lbsBibleRef" data-reference="Ephesians 2.1-3" data-version="esv" target="_blank">Ephesians 2:1-3</a>; <a href="http://biblia.com/bible/esv/1Timothy%202.13-14" class="lbsBibleRef" data-reference="1Timothy 2.13-14" data-version="esv" target="_blank">1Timothy 2:13-14</a>; <a href="http://biblia.com/bible/esv/1%20John%201.8" class="lbsBibleRef" data-reference="1 John 1.8" data-version="esv" target="_blank">1 John 1:8</a>. </em></p>
        <h2>Salvation</h2>
        <p>1. Salvation is wholly of God by grace through faith on the basis of the redemption by Christ Jesus, the merit of His shed blood, and not on the basis of human merit or works; and</p>
        <p>2. Salvation is an all-inclusive term from the special calling of God to justification by faith to regeneration and sanctification through the Holy Spirit to ultimate glorification in the presence of God; and</p>
        <p>3. Believers have two natures, namely the flesh and the spirit; that the believer is to grow in grace and in the knowledge of Christ, and to strive to live a life of holiness, characterized by his love of God and the love of his neighbours; and</p>
        <p>4. If the believer is truly regenerated or born again, he has eternal security through the election and grace of God.</p>
        <p><em><a href="http://biblia.com/bible/esv/John%201.12" class="lbsBibleRef" data-reference="John 1.12" data-version="esv" target="_blank">John 1:12</a>; <a href="http://biblia.com/bible/esv/John3.16" class="lbsBibleRef" data-reference="John3.16" data-version="esv" target="_blank">John3:16</a>; <a href="http://biblia.com/bible/esv/Romans%203.24-30" class="lbsBibleRef" data-reference="Romans 3.24-30" data-version="esv" target="_blank">Romans 3:24-30</a>; <a href="http://biblia.com/bible/esv/Romans%208.30-39" class="lbsBibleRef" data-reference="Romans 8.30-39" data-version="esv" target="_blank">Romans 8:30-39</a>; <a href="http://biblia.com/bible/esv/2%20Corinthians%205.21" class="lbsBibleRef" data-reference="2 Corinthians 5.21" data-version="esv" target="_blank">2 Corinthians 5:21</a>; <a href="http://biblia.com/bible/esv/Ephesians%201.7" class="lbsBibleRef" data-reference="Ephesians 1.7" data-version="esv" target="_blank">Ephesians 1:7</a>, <a href="http://biblia.com/bible/esv/1Thessalonians%204.3" class="lbsBibleRef" data-reference="1Thessalonians 4.3" data-version="esv" target="_blank">1Thessalonians 4:3</a>; <a href="http://biblia.com/bible/esv/1%20Peter%201.18-19" class="lbsBibleRef" data-reference="1 Peter 1.18-19" data-version="esv" target="_blank">1 Peter 1:18-19</a>.</em></p>
        <h2>Satan</h2>
        <p>We believe in the existence of Satan as a supernatural being, the deceiver and prince of this world; that he was defeated and judged by the death and resurrection of the Lord Jesus Christ, and therefore that his final doom is certain.</p>
        <p><em><a href="http://biblia.com/bible/esv/John%208.44" class="lbsBibleRef" data-reference="John 8.44" data-version="esv" target="_blank">John 8:44</a>; <a href="http://biblia.com/bible/esv/Ephesians%202.2" class="lbsBibleRef" data-reference="Ephesians 2.2" data-version="esv" target="_blank">Ephesians 2:2</a>; <a href="http://biblia.com/bible/esv/Hebrews%202.14" class="lbsBibleRef" data-reference="Hebrews 2.14" data-version="esv" target="_blank">Hebrews 2:14</a>. </em></p>
        <h2>The Church</h2>
        <p>1. All who place their faith in the Lord Jesus Christ are immediately placed by the Holy Spirit into one united spiritual body, the Church, the Bride of Christ, of which He is the Head; and</p>
        <p>2. The formation of the church, the body of Christ, began on the day of Pentecost and will be completed at the coming of Christ for His own at His second coming; and</p>
        <p>3. The establishment and continuity of local churches or assemblies is clearly taught and defined in the New Testament, and that the members of the one spiritual body are directed to associate themselves together in a local church or assembly.</p>
        <p>4. The responsibilities of leaders are to lead or rule as servants and to have Christ's authority in directing the church, the congregation of which are to submit themselves to their leadership; and</p>
        <p>5. The Scriptures stress discipleship within the context of the local church and mutual submission of all believers fellowshipping therein to each other; and</p>
        <p>6. Discipline of sinning members of the local church is to be administered in accordance with the Scriptures; and</p>
        <p>7. The purpose of the Church is to glorify God by the following: <br/>
        (a) Building herself up in the faith; and <br/>
        (b) Instruction of the Word; and <br/>
        (c) Fellowship; and <br/>
        (d) Keeping the ordinances of the Church; and <br/>
        (e) Advancing and communicating the Gospel to the entire world; and <br/>
        (f) Prayer.</p>
        <p>8. The ordinances of the local church which were instituted by Jesus Christ are two in <br/>
        number and are as follows: <br/>
        (a) Believer's Baptism by immersion; and <br/>
        (b) The Lord's Supper, in which all believers in the Lord Jesus Christ shall be invited to participate with due regard to the Scriptural warnings in <em><a href="http://biblia.com/bible/esv/1%20Corinthians%2011.27-29" class="lbsBibleRef" data-reference="1 Corinthians 11.27-29" data-version="esv" target="_blank">1 Corinthians 11:27-29</a></em>.</p>
        <h2>Separation</h2>
        <p>We believe that the Scriptures require separation to God from the world and from apostasy within the visible church. This doctrine is based upon God's eternal principle of division between truth and error, darkness and light, and His specific command to be separated from unbelievers and disobedient brethren.</p>
        <p><em><a href="http://biblia.com/bible/esv/2%20Corinthians%206.14-17" class="lbsBibleRef" data-reference="2 Corinthians 6.14-17" data-version="esv" target="_blank">2 Corinthians 6:14-17</a>, <a href="http://biblia.com/bible/esv/2%20Thessalonians%203.6" class="lbsBibleRef" data-reference="2 Thessalonians 3.6" data-version="esv" target="_blank">2 Thessalonians 3:6</a>, <a href="http://biblia.com/bible/esv/1%20Timothy%206.3-5" class="lbsBibleRef" data-reference="1 Timothy 6.3-5" data-version="esv" target="_blank">1 Timothy 6:3-5</a>; <a href="http://biblia.com/bible/esv/James%204.4" class="lbsBibleRef" data-reference="James 4.4" data-version="esv" target="_blank">James 4:4</a>; <a href="http://biblia.com/bible/esv/1%20John%202.15-16" class="lbsBibleRef" data-reference="1 John 2.15-16" data-version="esv" target="_blank">1 John 2:15-16</a>; <a href="http://biblia.com/bible/esv/2%20John%201.9-11" class="lbsBibleRef" data-reference="2 John 1.9-11" data-version="esv" target="_blank">2 John 1:9-11</a>. </em></p>
        <h2>Last Things</h2>
        <p>1. We believe in: the resurrection of the body, the judgment of the world by the Lord Jesus Christ, with eternal blessedness of the righteous and eternal punishment of the wicked.</p>
        <p><em><a href="http://biblia.com/bible/esv/Matthew%2025.32-34" class="lbsBibleRef" data-reference="Matthew 25.32-34" data-version="esv" target="_blank">Matthew 25:32-34</a>; <a href="http://biblia.com/bible/esv/Matthew%2025.46" class="lbsBibleRef" data-reference="Matthew 25.46" data-version="esv" target="_blank">46</a>; <a href="http://biblia.com/bible/esv/Revelation%2020.5-6" class="lbsBibleRef" data-reference="Revelation 20.5-6" data-version="esv" target="_blank">Revelation 20:5-6</a>, <a href="http://biblia.com/bible/esv/Revelation%2020.12-15" class="lbsBibleRef" data-reference="Revelation 20.12-15" data-version="esv" target="_blank">12-15</a>; and </em></p>
        <p>2. The imminent return of the Lord Jesus Christ.</p>
        <p><em><a href="http://biblia.com/bible/esv/Philippians%204.5" class="lbsBibleRef" data-reference="Philippians 4.5" data-version="esv" target="_blank">Philippians 4:5</a>; <a href="http://biblia.com/bible/esv/James%205.9" class="lbsBibleRef" data-reference="James 5.9" data-version="esv" target="_blank">James 5:9</a>; <a href="http://biblia.com/bible/esv/Revelation%2022.12" class="lbsBibleRef" data-reference="Revelation 22.12" data-version="esv" target="_blank">Revelation 22:12</a> </em></p>
        <p>(a) Believers will be caught up to meet the Lord in the air prior to the seven year tribulation</p>
        <p><em><a href="http://biblia.com/bible/esv/I%20Corinthians%2015.51-52" class="lbsBibleRef" data-reference="I Corinthians 15.51-52" data-version="esv" target="_blank">I Corinthians 15:51-52</a>; <a href="http://biblia.com/bible/esv/1%20Thessalonians%204.17" class="lbsBibleRef" data-reference="1 Thessalonians 4.17" data-version="esv" target="_blank">1 Thessalonians 4:17</a></em>; and</p>
        <p>(b) The Lord Jesus Christ will personally and visibly return to the earth with the saints to end the seven year tribulation and to reign with the saints for 1000 years.</p>
        <p><em><a href="http://biblia.com/bible/esv/Daniel%209.24-27" class="lbsBibleRef" data-reference="Daniel 9.24-27" data-version="esv" target="_blank">Daniel 9:24-27</a>; <a href="http://biblia.com/bible/esv/Matthew%2024.30-31" class="lbsBibleRef" data-reference="Matthew 24.30-31" data-version="esv" target="_blank">Matthew 24:30-31</a>; <a href="http://biblia.com/bible/esv/Matthew%2025.31-32" class="lbsBibleRef" data-reference="Matthew 25.31-32" data-version="esv" target="_blank">Matthew 25:31-32</a>; <a href="http://biblia.com/bible/esv/Revelation%2019.11" class="lbsBibleRef" data-reference="Revelation 19.11" data-version="esv" target="_blank">Revelation 19:11</a>; <a href="http://biblia.com/bible/esv/Revelation%2020.1-6" class="lbsBibleRef" data-reference="Revelation 20.1-6" data-version="esv" target="_blank">20:1-6</a><br/></em></p>
      </div>
    </div>
  )
}

export default WhatWeBelieveSection;
