name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: NPM Install
        run: sudo npm install

      - name: Build website
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy website to S3 bucket
        run: npm run deploy
